---
  Resources:
    VPCAula:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
        EnableDnsSupport: 'true'
        EnableDnsHostnames: 'true'

    PublicSubnetVPCA:
      Type: AWS::EC2::Subnet
      Properties:
        CidrBlock: 10.0.1.0/24
        VpcId: !Ref VPCAula

    PublicSubnetVPCB:
      Type: AWS::EC2::Subnet
      Properties:
        CidrBlock: 10.0.2.0/24
        VpcId: !Ref VPCAula

    PrivateSubnetVPCA:
      Type: AWS::EC2::Subnet
      Properties:
        CidrBlock: 10.0.3.0/24
        VpcId: !Ref VPCAula

    PrivateSubnetVPCB:
      Type: AWS::EC2::Subnet
      Properties:
        CidrBlock: 10.0.4.0/24
        VpcId: !Ref VPCAula

    IGW:
      Type: AWS::EC2::InternetGateway

    AttachIGW:
      Type: AWS::EC2::VPCGatewayAttachment
      DependsOn: IGW
      Properties:
        VpcId: !Ref VPCAula
        InternetGatewayId:
          Ref: IGW

    RT:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId: !Ref VPCAula

    RTtoIGW:
      Type: AWS::EC2::Route
      DependsOn: IGW
      Properties:
        RouteTableId: !Ref RT
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId: !Ref IGW

    RTAssoc:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId: !Ref RT
        SubnetId: !Ref PublicSubnetVPCA

    Instance: 
      Type: AWS::EC2::Instance
      DependsOn: RTAssoc
      Properties: 
        ImageId: ami-a4827dc9
        InstanceType: t2.micro
        SubnetId: !Ref PrivateSubnetVPCA
